In [ ]:
import torch
import numpy as np

In [ ]:
torch.__version__

'1.8.1+cu101'

# **Convert numby array into pytorch tensors**

In [ ]:
Array = [1,2,3,4,5]
my_list = np.array(Array)
my_list

array([1, 2, 3, 4, 5])

In [ ]:
my_list.dtype

dtype('int64')

In [ ]:
tensors = torch.from_numpy(my_list)
tensors

tensor([1, 2, 3, 4, 5])

In [ ]:
tensors.dtype

torch.int64

In [ ]:
tensors[1]                # indexing is as usual as numpy

tensor(2)

In [ ]:
tensors[2:5]              # slicing is as usual as numpy

tensor([3, 4, 5])

In [ ]:
tensors[4] = 10          # replace the existing element
tensors

tensor([ 1,  2,  3,  4, 10])

In [ ]:
my_list                 # when alteration is made on tensor , it is also getting registered in numpy array (coz both of them sharing same memory)

array([ 1,  2,  3,  4, 10])

In [ ]:
#To prevent the drawback mentioned at previous cell:
tensor_list = torch.tensor(my_list)
print(tensor_list)

tensor([ 1,  2,  3,  4, 10])


In [ ]:
tensor_list[4] = 8       
print(tensor_list)
print(my_list)

tensor([1, 2, 3, 4, 8])
[ 1  2  3  4 10]


In [ ]:
torch.zeros(2,3)                     # Zeros matrix

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
torch.ones(2,3)                      # ones matrix

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
X = torch.tensor(np.arange(0,10).reshape(2,5))          # reshape
X

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
X[:,1:3]                                                #slicing the columns

tensor([[1, 2],
        [6, 7]])

# **Arithmatic Operations**

In [ ]:
X = torch.tensor([1,2,3,4])
Y = torch.tensor([5,6,7,8])
Z = torch.tensor([9,10,11,12])
print(X + Y + Z)

tensor([15, 18, 21, 24])


In [ ]:
print(X * Y * Z)

tensor([ 45, 120, 231, 384])


In [ ]:
torch.add(X,Y)

tensor([ 6,  8, 10, 12])

In [ ]:
x = torch.tensor([1,2,3])
y = torch.tensor([4,5,6])
torch.add(x,y).sum()

tensor(21)

# **Dot and matrix multiplication**

In [ ]:
x = torch.tensor([1,2,3])
y = torch.tensor([4,5,6])
x.mul(y)

tensor([ 4, 10, 18])

In [ ]:
x.dot(y)

tensor(32)

In [ ]:
i = torch.tensor([[1,2,3],[4,5,6]])
j = torch.tensor([[7,8],[9,10],[11,12]])
torch.matmul(i,j)

tensor([[ 58,  64],
        [139, 154]])

In [ ]:
torch.mm(i,j)

tensor([[ 58,  64],
        [139, 154]])

In [ ]:
i@j

tensor([[ 58,  64],
        [139, 154]])

In [ ]:
print(torch.cuda.device_count())

1


In [ ]:
print(torch.cuda.get_device_name(0))

Tesla K80



# **Back Propogation - Pytorch**

In [ ]:
import torch

# Case 1 :
**y = x^2 >>>>> Derivative during back propagation >>>> dy/dx = 2x**

In [ ]:
x = torch.tensor(4.0,requires_grad=True )           # must be float
x

tensor(4., requires_grad=True)

In [ ]:
y = x**2
y

tensor(16., grad_fn=<PowBackward0>)

In [ ]:
y.backward()                      # Without using derivative equatioin,by the attribute - backward(), spontaneous computation is taking place
print(x.grad)

tensor(8.)


# Case 2:
**y = x^3 + x^2 >>>>>> Derivative during backpropagation >>>>>dy/dx=3x^2 + 2x^1**

In [ ]:
list = [[1.,2.,3.],[4.,5.,6.],[7.,8.,9.]]                   # must be float
torch_input = torch.tensor(list,requires_grad=True)
torch_input

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]], requires_grad=True)

In [ ]:
y=torch_input**3+torch_input**2
y

tensor([[  2.,  12.,  36.],
        [ 80., 150., 252.],
        [392., 576., 810.]], grad_fn=<AddBackward0>)

In [ ]:
z=y.sum()
z

tensor(2310., grad_fn=<SumBackward0>)

In [ ]:
z.backward()

In [ ]:
print(torch_input.grad)

tensor([[  5.,  16.,  33.],
        [ 56.,  85., 120.],
        [161., 208., 261.]])
